name: Publish Docker image

on:
  workflow_dispatch:
  push:
  repository_dispatch:
    types: [seanime_release]
  schedule:
    - cron: '0 0 * * *'  # Run daily to check for new releases

jobs:
  check_and_build:
    name: Check for new release and build Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get latest release of 5rahim/seanime
        id: seanime_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/5rahim/seanime/releases/latest | jq -r .tag_name)
          echo "LATEST_RELEASE=${LATEST_RELEASE}" >> $GITHUB_OUTPUT
          echo "Latest 5rahim/seanime release: ${LATEST_RELEASE}"

      - name: Check commit message for build flag
        id: check_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" == *"[build]"* ]]; then
            echo "FORCE_BUILD=true" >> $GITHUB_OUTPUT
            echo "Build force flag detected in commit message"
          else
            echo "FORCE_BUILD=false" >> $GITHUB_OUTPUT
            echo "No build force flag in commit message"
          fi

      - name: Check if new version is available
        id: check_version
        run: |
          CURRENT_VERSION=$(cat .version 2>/dev/null || echo "none")
          if [ "${{ steps.seanime_release.outputs.LATEST_RELEASE }}" != "${CURRENT_VERSION}" ]; then
            echo "NEW_VERSION=true" >> $GITHUB_OUTPUT
            echo "Newer version available"
          else
            echo "NEW_VERSION=false" >> $GITHUB_OUTPUT
            echo "No new version"
          fi

      - name: Check if build is needed
        id: check_build
        run: |
          if [ "${{ steps.check_version.outputs.NEW_VERSION }}" == "true" ] || [ "${{ steps.check_commit.outputs.FORCE_BUILD }}" == "true" ]; then
            echo "BUILD_NEEDED=true" >> $GITHUB_OUTPUT
            echo "Build needed due to new version or force flag"
          else
            echo "BUILD_NEEDED=false" >> $GITHUB_OUTPUT
            echo "No new version and no force flag. Skipping build."
          fi

      - name: Prepare the repository
        if: steps.check_build.outputs.BUILD_NEEDED == 'true'
        run: |
          chmod +x ./.docker/prepare.sh
          ./.docker/prepare.sh ${{ steps.seanime_release.outputs.LATEST_RELEASE }}
        shell: bash

      - name: Log in to Docker Hub
        if: steps.check_build.outputs.BUILD_NEEDED == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        if: steps.check_build.outputs.BUILD_NEEDED == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ncrqnt/seanime
          tags: |
            type=raw,value=${{ steps.seanime_release.outputs.LATEST_RELEASE }}
            type=raw,value=latest

      - name: Build and push Docker image
        if: steps.check_build.outputs.BUILD_NEEDED == 'true'
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./.docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SEANIME_VERSION=${{ steps.seanime_release.outputs.LATEST_RELEASE }}

      - name: Update version file
        if: steps.check_version.outputs.NEW_VERSION == 'true'
        run: |
          echo "${{ steps.seanime_release.outputs.LATEST_RELEASE }}" > .version
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .version
          git commit -m "Update to seanime version ${{ steps.seanime_release.outputs.LATEST_RELEASE }}"
          git push
